package com.sample
 
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.sample.Dish;
import com.sample.Window;
import com.sample.FinalWindow;
import com.sample.Updater;


rule "skladniki"
	salience 11
	when d: Dish(!attributeExist("skladniki"))
	then
		Window w = new Window(d, "Jakie masz dostępne produkty?", "skladniki", "check", 
		new String[] 
		{"bagietka","bułka","cebula","chleb","ciasto francuskie","dżem",
		"herbata","jajka","kapusta","kapusta kiszona","kasza","kiełbasa",
		"makaron","masło","mąka","mięso","mięso mielone","miód","mleko",
		"nutella","ogórek","olej","papryka","parówki","pasztet","pieczarki",
		"pierogi","piwo","płatki","pomidor","ryż","ser pleśniowy","ser twarogowy",
		"ser żółty","sos do spaghetti","szynka","śmietana","ziemniaki"});
		update(w.d);
end 

rule "pic_jesc"
	salience 10
	when d: Dish( !attributeExist("pic_jesc") )
	then
		Window w = new Window(d, "Chcesz się napić, czy coś zjeść?", "pic_jesc", "radio", new String[] {"pić", "jeść"});
		update(w.d);
end

rule "smak"
	salience 10
	when d: Dish( !attributeExist("smak") )
	then
		Window w = new Window(d, "Jaki smak preferujesz?", "smak", "check", new String[] {"słodki", "wytrawny", "słony", "gorzki","kwaśny"});
		update(w.d);
end

rule "czas" 
	salience 10
	when d: Dish( !attributeExist("czas") )
	then
		Window w = new Window(d, "Ile masz czasu na przygotowanie posiłku?", "czas", "radio",
		new String[] {"0 min", "10 min", "30 min", "60 min", "więcej"});
		update(w.d);
end

rule "sprzet"
	salience 10
	when d: Dish( !attributeExist("sprzet") && attributeContain("cieplo_zimno","ciepło") )
	then
		Window w = new Window(d, "Co z wymienionych rzeczy masz do dyspozycji?", "sprzet", "check", 
		new String[] {"kuchenka", "grill", "piekarnik", "mikrofalówka", "garnek", "patelnia",
		"toster", "czajnik", "frytkownica"});
		update(w.d);
end

rule "cieplo_zimno"
	salience 10
	when d: Dish( !attributeExist("cieplo_zimno") && !attributeContain("czas", "0 min") && attributeExist("czas"))
	then
		Window w = new Window(d, "Chcesz danie na ciepło czy na zimno?", "cieplo_zimno", "radio", new String[] {"ciepło", "zimno"});
		update(w.d);
end

rule "cieplo_zimno_brak_czasu"
	salience 10
	when d: Dish( !attributeExist("cieplo_zimno") && attributeContain("czas", "0 min"))
	then
		Updater u = new Updater(d, "cieplo_zimno", new String[] {"zimno"});		
		update(u.d);
end

rule "wegetarianskie"
	salience 10
	when d: Dish( !attributeExist("wegetarianskie") && attributeExist("skladniki") && 
	(attributeContain("skladniki", "kiełbasa") || attributeContain("skladniki", "mięso") || attributeContain("skladniki", "mięso mielone") ||
	attributeContain("skladniki", "parówki") || attributeContain("skladniki", "pasztet")))
	then
		Window w = new Window(d, "Czy danie musi być wegetariańskie?", "wegetarianskie", "radio", new String[] {"tak", "nie"});
		update(w.d);
end

rule "zmywanie"
	salience 10
	when d: Dish( !attributeExist("zmywanie") && !attributeContain("czas", "0 min") && attributeExist("czas"))
	then
		Window w = new Window(d, "Czy może być dużo naczyć do zmywania po posiłku?", "zmywanie", "radio", new String[] {"tak", "nie"});
		update(w.d);
end

rule "zmywanie_brak_czasu"
	salience 10
	when d: Dish( !attributeExist("zmywanie") && attributeContain("czas", "0 min"))
	then		
		Updater u = new Updater(d, "zmywanie", new String[] {"nie"});	
		update(u.d);
end

rule "glodny"
	salience 10
	when d: Dish( !attributeExist("glodny") && attributeContain("pic_jesc", "jeść"))
	then
		Window w = new Window(d, "Jak bardzo jesteś głodny?", "glodny", "radio", new String[] {"lekko", "średnio", "bardzo"});
		update(w.d);
end

rule "bogato"
	salience 10
	when d: Dish( !attributeExist("bogato"))
	then
		Window w = new Window(d, "Dzisiaj na bogato, czy bieda?", "bogato", "radio", new String[] {"tak, na bogato", "bieda"});		
		update(w.d);
end

//Wynikowe:

rule "frytki"
	salience 10
	when d: Dish( !attributeContain("danie","frytki") && attributeContain("skladniki", "ziemniaki") && attributeContain("skladniki", "olej")
				&& (attributeContain("sprzet", "frytkownica") || attributeContain("sprzet", "patelnia")) && attributeContain("cieplo_zimno", "ciepło")
				&& (attributeContain("glodny", "bardzo") || attributeContain("glodny", "średnio")) && attributeContain("zmywanie", "tak") &&
				(attributeContain("czas", "30 min") || attributeContain("czas", "60 min") || attributeContain("czas", "więcej")) && 
				attributeContain("pic_jesc", "jeść") && attributeContain("smak", "słony"))
	then
		new ResultWindow(d, "frytki", "Proponujemy frytki ", "Czy odpowida Ci to danie?");
end

rule "hotdog"
	salience 10
	when d: Dish( !attributeContain("danie","hotdog") && attributeContain("skladniki","bagietka") && attributeContain("skladniki","parówki")
		&& attributeContain("pic_jesc","jeść") && ( attributeContain("czas","10 min") || attributeContain("czas","30 min") || attributeContain("czas","60 min")
		|| attributeContain("czas","więcej")) && attributeContain("sprzet","mikrofalówka") && attributeContain("cieplo_zimno","ciepło") && 
		attributeContain("wegetarianskie","nie") && attributeContain("glodny","lekko") && attributeContain("bogato","bieda"))
	then
		new ResultWindow(d, "hotdog", "Hot Dog będzie dobrym wyborem. Mówiesz, że bieda więc z samą bulką i parówką xD", "Jesteś Za?");
end

rule "bigos"
	salience 10
	when d: Dish( !attributeContain("danie","bigos") && attributeContain("skladniki","cebula") && (attributeContain("skladniki","kapusta") 
		|| attributeContain("skladniki","kapusta kiszona")) && attributeContain("skladniki","kiełbasa") && attributeContain("skladniki","mięso")
		&& attributeContain("skladniki","olej") && attributeContain("pic_jesc","jeść") && attributeContain("smak","kwaśny") &&
		(attributeContain("czas","60 min") || attributeContain("czas","więcej")) && attributeContain("sprzet","kuchenka") && attributeContain("sprzet","garnek")
		&& attributeContain("sprzet","patelnia") && attributeContain("cieplo_zimno","ciepło") && attributeContain("wegetarianskie","nie") && attributeContain("zmywanie","tak")
		&& (attributeContain("glodny","średnio") || attributeContain("glodny","bardzo")) && attributeContain("bogato","tak, na bogato"))
	then
		new ResultWindow(d, "bigos", "Widzę, że możemy dzisiaj zaszaleć. Bigos!!! Coś pysznego :3 ", "Pasuje?");
end

rule "ziemniaki_ze_smietana"
	salience 10
	when d: Dish( !attributeContain("danie","ziemniaki_ze_smietana") && attributeContain("skladniki","śmietana") && attributeContain("skladniki","ziemniaki")
	&& attributeContain("pic_jesc","jeść") && (attributeContain("smak","słony") || attributeContain("smak","wytrawny")) && (attributeContain("czas","30 min") || 
	attributeContain("czas","60 min") || attributeContain("czas","więcej")) && attributeContain("sprzet","kuchenka") && (attributeContain("sprzet","garnek") || 
	attributeContain("sprzet","patelnia")) && attributeContain("zmywanie","tak") && attributeContain("bogato","bieda"))
	then
		new ResultWindow(d, "ziemniaki_ze_smietana", "No nie poszalejemy. Ziemniaki ze śmietaną  ", "Pasuje?");
end	

rule "kanapki"
	salience 10
	when d: Dish( !attributeContain("danie","kanapki") && (attributeContain("skladniki","bagietka") || attributeContain("skladniki","bułka")
	|| attributeContain("skladniki","chleb")) && (attributeContain("skladniki","cebula") || attributeContain("skladniki","dżem") || attributeContain("skladniki","jajka")
	|| attributeContain("skladniki","kiełbasa") || attributeContain("skladniki","masło") || attributeContain("skladniki","mięso") || attributeContain("skladniki","miód")
	|| attributeContain("skladniki","nutella") || attributeContain("skladniki","ogórek") || attributeContain("skladniki","papryka") || attributeContain("skladniki","parówki")
	|| attributeContain("skladniki","pasztet") || attributeContain("skladniki","pieczarki") || attributeContain("skladniki","pomidor") || attributeContain("skladniki","ser pleśniowy")
	|| attributeContain("skladniki","ser twarogowy") || attributeContain("skladniki","ser żółty") || attributeContain("skladniki","szynka")) && 
	attributeContain("pic_jesc","jeść") && (attributeContain("smak","słodki") || attributeContain("smak","słony") || attributeContain("smak","wytrawny")) &&
	(attributeContain("czas","10 min") || attributeContain("czas","30 min") || attributeContain("czas","60 min") || attributeContain("czas","więcej"))
	&& (attributeContain("glodny","lekko") || attributeContain("glodny","średnio")) && attributeContain("bogato","bieda"))
	then
		new ResultWindow(d, "kanapki", "Coś tam się znajdzie. Zrób se kanapki ", "Może być?");
end	

//jedyna słuszna wygoda marki dziura w dupie iksde lol :----DDDDDDD

rule "burger"
    salience 10
    when d: Dish (
        !attributeContain("danie", "burger") &&
        attributeContain("skladniki","bułka") &&
        attributeContain("skladniki","mięso") &&
        attributeContain("skladniki","ogórek") &&
        attributeContain("skladniki","pomidor") &&
        attributeContain("skladniki","ser żółty") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słodki") ||
        attributeContain("smak","słony") ||
        attributeContain("smak","wytrawny")) &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        (attributeContain("sprzet","piekarnik") ||
        attributeContain("sprzet","mikrofalówka") ||
        (attributeContain("sprzet","patelnia") &&
        attributeContain("sprzet","kuchenka"))) &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","nie") &&
        attributeContain("glodny","średnio") &&
        (attributeContain("bogato","tak, na bogato") ||
        attributeContain("bogato","bieda"))
    )
    then
        new ResultWindow(d, "burger", "<freedom mode on> TYLKO BURGER <freedom mode off> ", "Gra gitara?");
end

rule "gołąbki"
    salience 10
    when d: Dish (
        !attributeContain("danie", "gołąbki") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("skladniki","kapusta") &&
        (attributeContain("skladniki","kasza") ||
        attributeContain("skladniki","ryż")) &&
        attributeContain("skladniki","mięso mielone") &&
        attributeContain("skladniki","pomidor") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        (attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","bardzo") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "gołąbki", "Jak tak bardzo chce Ci się robić gołąbki, to jest to git opcja xD ", "Pasi?");
end

rule "kapuśniak"
    salience 10
    when d: Dish (
        !attributeContain("danie", "kapuśniak") &&
        attributeContain("skladniki","cebula") &&
        (attributeContain("skladniki","kapusta") ||
        attributeContain("skladniki","kapusta kiszona")) &&
        attributeContain("skladniki","mięso") &&
        attributeContain("skladniki","kiełbasa") &&
        attributeContain("skladniki","olej") &&                        
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","kwaśny") &&        
        attributeContain("czas","więcej") &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","tak") &&
        (attributeContain("glodny","bardzo") ||
        attributeContain("glodny","średnio")) &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "kapuśniak", "Jak masz dużo wolnego czasu to polecam kapuśniak, pychotka", "Zjadłbyś, prawda?");
end

rule "pierogi"
    salience 10
    when d: Dish(
        !attributeContain("danie","pierogi") &&
        attributeContain("skladniki","pierogi") &&        
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słony") ||
        attributeContain("smak","wytrawny")) && 
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        (attributeContain("sprzet","patelnia") ||
        attributeContain("sprzet","garnek")) && 
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&
        (attributeContain("glodny","bardzo") ||
        attributeContain("glodny","średnio"))        
    )
    then
        new ResultWindow(d, "pierogi", "Pierogi to też jakaś opcja", "Chcesz to jeść?");
end

rule "jajecznica"
    salience 10
    when d: Dish(
        !attributeContain("danie","jajecznica") &&
        attributeContain("skladniki","jajka") &&
        (attributeContain("skladniki","masło") ||
        attributeContain("skladniki","olej")) &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&
        (attributeContain("glodny","lekko") ||
        attributeContain("glodny","średnio")) &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "jajecznica", "Zawsze możesz sobie zrobić też jajecznicę (chociaż ile można ją jeść...) ", "Nie zbrzydła Ci jeszcze? Chcesz ją zjeść?");
end

rule "spaghetti"
    salience 10
    when d: Dish(
        !attributeContain("danie","spaghetti") &&
        attributeContain("skladniki","makaron") &&
        attributeContain("skladniki","sos do spaghetti") &&
        attributeContain("skladniki","mięso mielone") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słony") ||
        attributeContain("smak","wytrawny")) &&         
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&
        (attributeContain("glodny","bardzo") ||
        attributeContain("glodny","średnio")) &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "spaghetti", "Spaghetti zawsze spoko", "Podzielasz moje zdanie?");
end

rule "parówki_z_makaronem"
    salience 10
    when d: Dish(
        !attributeContain("danie","parówki_z_makaronem") &&
        attributeContain("skladniki","makaron") &&        
        attributeContain("skladniki","parówki") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słony") ||
        attributeContain("smak","wytrawny")) &&         
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&        
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "parówki_z_makaronem", "No cóż poeksperymentujmy. Parówki z makaronem :D", "Lubisz takie?");
end

rule "jajecznica_z_kiełbasą"
    salience 10
    when d: Dish(
        !attributeContain("danie","jajecznica_z_kiełbasą") &&
        attributeContain("skladniki","jajka") &&
        (attributeContain("skladniki","masło") ||
        attributeContain("skladniki","olej")) &&
        attributeContain("skladniki","kiełbasa") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","tak, na bogato")
        )
    then
        new ResultWindow(d, "jajecznica_z_kiełbasą", "A może jajecznica na sterydach? O ile nie szkoda Ci kiełbasy na takie cuda.", "Może być?");
end

rule "jajka_gotowane"
    salience 10
    when d: Dish(
        !attributeContain("danie","jajka_gotowane") &&
        attributeContain("skladniki","jajka") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "jajka_gotowane", "Jajka gotowane. Musisz tylko trochę na nie poczekać xD", "Pasi?");
end

rule "twaróg_ze_śmietaną"
    salience 10
    when d: Dish(
        !attributeContain("danie","twaróg_ze_śmietaną") &&
        attributeContain("skladniki","ser twarogowy") &&
        attributeContain("skladniki","śmietana") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("zmywanie","tak") &&
        (attributeContain("glodny","lekko") ||
        attributeContain("glodny","średnio")) &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "twaróg_ze_śmietaną", "Twarożek ze śmietaną i cebulką. To jest to", "Lubisz?");
end

rule "sałatka_z_pomidorów"
    salience 10
    when d: Dish(
        !attributeContain("danie","sałatka_z_pomidorów") &&
        attributeContain("skladniki","pomidor") &&
        attributeContain("skladniki","śmietana") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "sałatka_z_pomidorów", "Sałatka ze świeżych pomidorków z cebulką w śmietanie", "Zjadłbyś?");
end

rule "mizeria"
    salience 10
    when d: Dish(
        !attributeContain("danie","mizeria") &&
        attributeContain("skladniki","ogórek") &&
        attributeContain("skladniki","śmietana") &&        
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","lekko")        
    )
    then
        new ResultWindow(d, "mizeria", "Masz ogórki i śmietanę ... zrób mizerię :)", "Dobry pomysł?");
end

rule "płatki_z_mlekiem"
    salience 10
    when d: Dish(
        !attributeContain("danie","płatki_z_mlekiem") &&
        attributeContain("skladniki","płatki") &&
        attributeContain("skladniki","mleko") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słodki") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "sałatka_z_pomidorów", "Sałatka ze świeżych pomidorków z cebulką w śmietanie", "Zjadłbyś?");
end

rule "dżem"
    salience 9
    when d: Dish(
        !attributeContain("danie","dżem") &&
        attributeContain("skladniki","dżem") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słodki") &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "dżem", "Ale bieda, żryj dżem.", "Wystarczy?");
end

rule "parówki"
    salience 9
    when d: Dish(
        !attributeContain("danie","parówki") &&
        attributeContain("skladniki","parówki") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","wytrawny") &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "parówki", "Od biedy musza wystarczyć parówki na zimno.", "Idziesz na to?");
end

rule "parówki_z_mikrofalówki"
    salience 10
    when d: Dish(
        !attributeContain("danie","parówki_z_mikrofalówki") &&
        attributeContain("skladniki","parówki") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","wytrawny") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "parówki_z_mikrofalówki", "Od biedy musza wystarczyć parówki. Podgrzej w mikrofali", "Idziesz na to?");
end

rule "parówki_gotowane"
    salience 10
    when d: Dish(
        !attributeContain("danie","parówki_gotowane") &&
        attributeContain("skladniki","parówki") &&      
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("sprzet","garnek") &&
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "parówki_gotowane", "No cóż, znowu parówki. Ugotuj sobie", "Przełkniesz to?");
end

rule "naleśniki"
    salience 10
    when d: Dish(
        !attributeContain("danie","naleśniki") &&
        attributeContain("skladniki","mąka") &&      
        attributeContain("skladniki","mleko") &&
        attributeContain("skladniki","jajka") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        attributeContain("sprzet","kuchenka") &&
        attributeContain("sprzet","patelnia") &&
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","ciepło") &&        
        (attributeContain("glodny","średnio") ||
        attributeContain("glodny","bardzo")) &&
        attributeContain("zmywanie","tak") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "naleśniki", "Zrób naleśniki, będzie pycha", "Robisz?");
end

rule "parówki_w_cieście_francuskim"
    salience 10
    when d: Dish(
        !attributeContain("danie","parówki_w_cieście_francuskim") &&
        attributeContain("skladniki","parówki") &&
        attributeContain("skladniki","ciasto francuskie") &&
        attributeContain("skladniki","ser żółty") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        attributeContain("sprzet","piekarnik") &&
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "parówki_w_cieście_francuskim", "To na bogato, parówki w cieście francuskim :P", "Już Ci cieknie ślinka?");
end

rule "tosty"
    salience 10
    when d: Dish(
        !attributeContain("danie","tosty") &&
        attributeContain("skladniki","ser żółty") &&
        attributeContain("skladniki","chleb") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        (attributeContain("sprzet","piekarnik") ||
        attributeContain("sprzet","toster")) &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","ciepło") &&        
        (attributeContain("glodny","lekko") ||
        attributeContain("glodny","średnio")) &&
        attributeContain("zmywanie","tak") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "parówki_w_cieście_francuskim", "To na bogato, parówki w cieście francuskim :P", "Już Ci cieknie ślinka?");
end

rule "bułka"
    salience 9
    when d: Dish(
        !attributeContain("danie","bułka") &&
        attributeContain("skladniki","bułka") &&
        attributeContain("pic_jesc","jeść") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słony")) &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "bułka", "Jak serio krucho z kasą to szamaj suche bułki", "Ok?");
end

rule "mleko"
    salience 9
    when d: Dish(
        !attributeContain("danie","mleko") &&
        attributeContain("skladniki","mleko") &&
        attributeContain("pic_jesc","pić") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "mleko", "Pij mleko będziesz wielki!!", "Pijesz?");
end

rule "mleko_z_miodem"
    salience 10
    when d: Dish(
        !attributeContain("danie","mleko_z_miodem") &&
        attributeContain("skladniki","mleko") &&
        attributeContain("skladniki","miód") &&
        attributeContain("pic_jesc","pić") &&        
        attributeContain("smak","słodki") &&        
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        (attributeContain("cieplo_zimno","zimno") ||
        attributeContain("cieplo_zimno","ciepło")) &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "mleko_z_miodem", "Mhmmmmm, mleczko z miodkiem ...", "Zasmakujesz?");
end

rule "herbata"
    salience 10
    when d: Dish(
        !attributeContain("danie","herbata") &&
        attributeContain("pic_jesc","pić") &&
        (attributeContain("smak","słodki") ||
        attributeContain("smak","gorzki")) &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","czajnik") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","nie") &&
        attributeContain("glodny","lekko") &&
        (attributeContain("bogato","tak, na bogato") ||
        attributeContain("bogato","bieda")) // zawsze można mieć jakieś za over 9000 cebulionów
    )
    then
        new ResultWindow(d, "herbata", "Proponuję herbatkę u Tadka, najlepszego komika wojennego ", "Czy lubisz Drozdę?");
end

rule "woda"
    salience 9
    when d: Dish(
        !attributeContain("danie","woda") &&        
        attributeContain("pic_jesc","pić") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","słodki") ||
        attributeContain("smak","słony")) &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "woda", "Podobno woda jest najzdrowsza, więc pij na zdrowie.", "Pijesz?");
end

rule "woda_po_kapuście"
    salience 9
    when d: Dish(
        !attributeContain("danie","woda") &&        
        attributeContain("pic_jesc","pić") &&
        attributeContain("smak","kwaśny") &&
        attributeContain("skladniki","kapusta kiszona") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "woda_po_kapuście", "Ciekawe preferencja. Wyciśnij sobie wodę z kapusty kiszonej xD", "Pasuje Ci to?");
end

rule "piwo"
    salience 10
    when d: Dish(
        !attributeContain("danie","piwo") &&
        attributeContain("skladniki","piwo") &&
        attributeContain("pic_jesc","pić") &&
        (attributeContain("smak","wytrawny") ||
        attributeContain("smak","gorzki") ||
        attributeContain("smak","słodki")) &&
        (attributeContain("czas","0 min") ||
        attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("cieplo_zimno","zimno") &&
        (attributeContain("bogato","tak, na bogato") ||
        attributeContain("bogato","bieda"))
    )
    then
        new ResultWindow(d, "piwo", "Zawsze jest dobra pora na hehe piwko :D", "Pijemy?!");
end

rule "kasza_z_miodem"
    salience 10
    when d: Dish(
        !attributeContain("danie","kasza_z_miodem") &&
        attributeContain("skladniki","kasza") &&
        attributeContain("skladniki","miód") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słodki") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","garnek") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "kasza_z_miodem", "Jak into miód, zawsze możesz into biedacką kaszę z miodem :D", "Dasz radę to zjeść?");
end

rule "kiełbasa_gotowana"
    salience 10
    when d: Dish(
        !attributeContain("danie","kielbasa_gotowana") &&
        attributeContain("skladniki","kiełbasa") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","garnek") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "kiełbasa_gotowana", "Na szybko możesz ugotować kiełbachę - o ile nie szkoda Ci jej na grilla.", "Dajesz soga?");
end

rule "kiełbasa_smażona"
    salience 10
    when d: Dish(
        !attributeContain("danie","kiełbasa_smażona") &&
        attributeContain("skladniki","kiełbasa") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "kiełbasa_smażona", "Na szybko możesz kiełbachę wrzucić na patelnię - o ile nie szkoda Ci jej na grilla.", "Dajesz soga?");
end

rule "kiełbasa_smażona_z_cebulą"
    salience 10
    when d: Dish(
        !attributeContain("danie","kiełbasa_smażona") &&
        attributeContain("skladniki","kiełbasa") &&
        attributeContain("skladniki","olej") &&
        attributeContain("skladniki","cebula") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("glodny","średnio") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "kiełbasa_smażona_z_cebulą", "Opcja semi-bieda - kiełbasa smażona z cebulą.", "Czy jesteś cebularzem?");
end

rule "kotlet_z_jajek"
    salience 10
    when d: Dish(
        !attributeContain("danie","kotlet_z_jajek") &&
        attributeContain("skladniki","chleb") &&
        attributeContain("skladniki","jajka") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","10 min") ||
        attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","lekko") &&
        attributeContain("bogato","bieda")
    )
    then
        new ResultWindow(d, "kotlet_z_jajek", "BIEDA ALERT - legendarny kotlet z jajek na podstawie przepisu by Tomasz Bieniek!", "Czy jesteś desperatem?");
end

rule "kotlet_z_kaszą"
    salience 10
    when d: Dish(
        !attributeContain("danie","kotlet_z_kaszą") &&
        attributeContain("skladniki","kasza") &&
        attributeContain("skladniki","mięso") &&
        attributeContain("skladniki","olej") &&
        attributeContain("pic_jesc","jeść") &&
        attributeContain("smak","słony") &&
        (attributeContain("czas","30 min") ||
        attributeContain("czas","60 min") ||
        attributeContain("czas","więcej")) &&
        attributeContain("sprzet","garnek") &&
        attributeContain("sprzet","patelnia") &&
        attributeContain("cieplo_zimno","ciepło") &&
        attributeContain("wegetarianskie","nie") &&
        attributeContain("zmywanie","tak") &&
        attributeContain("glodny","bardzo") &&
        attributeContain("bogato","tak, na bogato")
    )
    then
        new ResultWindow(d, "kotlet_z_kaszą", "Wyczuwam bogactwo - kotlet z kaszą! Radzę ukryć przed współlokatorem :D", "Mam nadzieję, że pasuje?");
end

rule "void"
	salience 1
	when d: Dish()
	then
		new FinalWindow("Niestety pozostaje Ci tylko \"Jajecznica studencka\".");
end 
