package com.sample
 
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import com.sample.Dish;
import com.sample.Window;
import com.sample.FinalWindow;
import com.sample.Updater;


rule "skladniki"
	salience 11
	when d: Dish(!attributeExist("skladniki"))
	then
		Window w = new Window(d, "Jakie masz dostêpne produkty?", "skladniki", "check", 
		new String[] 
		{"bagietka","bu³ka","cebula","chleb","ciasto francuskie","d¿em",
		"herbata","jajka","kapusta","kapusta kiszona","kasza","kie³basa",
		"makaron","mas³o","m¹ka","miêso","miêso mielone","miód","mleko",
		"nutella","ogórek","olej","papryka","parówki","pasztet","pieczarki",
		"pierogi","piwo","p³atki","pomidor","ry¿","ser pleœniowy","ser twarogowy",
		"ser ¿ó³ty","sos do spagetti","szynka","œmietana","ziemniaki"});
		update(w.d);
end 

rule "smak"
	salience 10
	when d: Dish( !attributeExist("smak") )
	then
		Window w = new Window(d, "Jaki smak preferujesz?", "smak", "radio", new String[] {"s³odki", "s³ony", "gorzki","kwaœny"});
		update(w.d);
end

rule "czas" 
	salience 10
	when d: Dish( !attributeExist("czas") )
	then
		Window w = new Window(d, "Ile masz czasu na przygotowanie posi³ku?", "czas", "radio",
		new String[] {"0 min", "10 min", "20 min","30 min", "60 min", "wiêcej"});
		update(w.d);
end

rule "sprzet"
	salience 10
	when d: Dish( !attributeExist("sprzet") && !attributeContain("czas", "0 min") && attributeExist("czas") && attributeContain("cieplo_zimno","ciep³o") )
	then
		Window w = new Window(d, "Co z wymienionych rzeczy masz do dyspozycji?", "sprzet", "check", 
		new String[] {"kuchenka", "grill", "piekarnik", "mikrofalówka", "garnek", "patelnia",
		"toster", "czajnik"});
		update(w.d);
end

rule "cieplo_zimno"
	salience 10
	when d: Dish( !attributeExist("cieplo_zimno") && !attributeContain("czas", "0 min") && attributeExist("czas"))
	then
		Window w = new Window(d, "Chcesz danie na ciep³o czy na zimno?", "cieplo_zimno", "radio", new String[] {"ciep³o", "zimno"});
		update(w.d);
end

rule "cieplo_zimno_brak_czasu"
	salience 10
	when d: Dish( !attributeExist("cieplo_zimno") && attributeContain("czas", "0 min"))
	then
		Updater u = new Updater(d, "cieplo_zimno", new String[] {"ciep³o"});		
		update(u.d);
end

rule "wegetarianskie"
	salience 10
	when d: Dish( !attributeExist("wegetarianskie") && attributeExist("skladniki") && 
	(attributeContain("skladniki", "kie³basa") || attributeContain("skladniki", "miêso") || attributeContain("skladniki", "miêso mielone") ||
	attributeContain("skladniki", "parówki") || attributeContain("skladniki", "pasztet")))
	then
		Window w = new Window(d, "Czy danie musi byæ wegetariañskie?", "wegetarianskie", "radio", new String[] {"tak", "nie"});
		update(w.d);
end

rule "zmywanie"
	salience 10
	when d: Dish( !attributeExist("zmywanie") && !attributeContain("czas", "0 min") && attributeExist("czas"))
	then
		Window w = new Window(d, "Czy mo¿e byæ du¿o naczyæ do zmywania po posi³ku?", "zmywanie", "radio", new String[] {"tak", "nie"});
		update(w.d);
end
//Wynikowe:

rule "wynik_wlasciciel_sklepu"
	salience 1
	when d: Dish( attributeContain("zylka_handlowca", "tak") && attributeContain("dzialalnosc", "tak") && attributeContain("pieniadze", "tak"))
	then
		new FinalWindow("Zawod wybrany dla ciebie to wlasciciel sklepu!");
end


rule "void"
	salience 1
	when d: Dish()
	then
		new FinalWindow("Niestety pozostaje Ci tylko \"Jajecznica studencka\".");
end 
